### ISSUE TITLE
[Bug] Crash after updating to latest release

### ISSUE THREAD

**Issue by QuantumQuacken** [WoWs-Builder-Team/WoWs-ShipBuilder#248]
System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)

I assume it's v2.1.24

Upon launching the application, a blank window appears with the same dimensions as the window that appears after opening a ship's page.

<details>
  <summary>Details of the error message</summary>

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WoWsShipBuilder
    Assembly Version: 2.1.24.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Hosting
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Splat
    Assembly Version: 14.6.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.DesktopRuntime
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Controls
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Base
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Styling
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Input
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Interactivity
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Layout
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Visuals
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Animation
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WoWsShipBuilder.Common
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Sentry
    Assembly Version: 3.33.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
SquirrelLib
    Assembly Version: 2.9.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
WoWsShipBuilder.DataStructures
    Assembly Version: 3.1.6.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
NLog
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
NLog.Extensions.Logging
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
ReactiveUI
    Assembly Version: 18.4.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.EventLog
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Configuration
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Options.ConfigurationExtensions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Console
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.Debug
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.Logging.EventSource
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Sentry.NLog
    Assembly Version: 3.33.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.Compression
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Mail
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Sockets
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq.Expressions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
TestableIO.System.IO.Abstractions
    Assembly Version: 19.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
TestableIO.System.IO.Abstractions.Wrappers
    Assembly Version: 19.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components.WebView.WindowsForms
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
MudBlazor
    Assembly Version: 6.2.5.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Http
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components.WebView
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.JSInterop
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.AspNetCore.Components.Web
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reactive
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
ReactiveUI.Blazor
    Assembly Version: 18.4.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reactive.Wasm
    Assembly Version: 1.2.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.ReactiveUI
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.FileSystem.DriveInfo
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Desktop
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Skia
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Win32
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.MicroCom
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Data.Common
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Security
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Cryptography
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
SharpCompress
    Assembly Version: 0.31.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Text.Encoding.CodePages
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Xml.XDocument
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Private.Xml.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.OpenGL
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
SkiaSharp
    Assembly Version: 2.88.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Markup.Xaml
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Themes.Default
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Avalonia.Markup
    Assembly Version: 0.10.21.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Buffers
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.Quic
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Net.NameResolution
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Claims
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
HarfBuzzSharp
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Tasks.Parallel
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
JsonSubTypes
    Assembly Version: 2.0.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1370.28
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1370.28
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
DynamicData
    Assembly Version: 7.13.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Extensions.FileProviders.Composite
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------

************** JIT Debugging **************
```

</details>

**Comment by iTTou** [comment]
Nothing we can do about that. If something is missing, either the update framework we use has a bug on its side or something else like the antivirus interferes with the update process.

**Comment by floribe2000** [comment]
Please check if there is a log file in `%APPDATA%\WoWsShipBuilder\logs` and if it contains any more details about this error.

Unfortunately, the information included in your report is not enough to identify the missing file. After that, please try to re-run the current installer. It should fix the problem, if not, please contact us via discord so that we can try to track down the issue.

As itto wrote, it is most likely that an anti virus program blocked some files during the update process but we cannot say for sure without details. This does not seem to be a common issue since you were the only one reporting it so far.

**Comment by QuantumQuacken** [comment]
<details>
<summary>Older version opening with update to current non-working version </summary>

```2023-08-20 12:15:57.0056|Info|WoWsShipBuilder.UI.Program|------------------------------
2023-08-20 12:15:57.0356|Info|WoWsShipBuilder.UI.Program|Starting application...
2023-08-20 12:15:58.1120|Info|WoWsShipBuilder|Trying to load settings from settings file...
2023-08-20 12:15:58.1598|Info|WoWsShipBuilder|Settings initialized
2023-08-20 12:15:58.3847|Info|WoWsShipBuilder.UI.App|AutoUpdate Enabled: true
2023-08-20 12:15:58.3923|Info|WoWsShipBuilder.UI.App|Current version: 1.6.3.0
2023-08-20 12:15:58.3923|Info|WoWsShipBuilder.UI.App|Update manager initialized
2023-08-20 12:15:58.6538|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|UpdateCheck triggered. Checking whether update should execute...
2023-08-20 12:15:58.6538|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Starting update check...
2023-08-20 12:15:58.6538|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Checking json file versions for server type "Live"
2023-08-20 12:15:59.0026|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Local data version (51) is older than online data version (53). Selecting files for update...
2023-08-20 12:15:59.0026|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Updating 68 files...
2023-08-20 12:15:59.0135|Warn|WoWsShipBuilder.Core.HttpClients.AwsClient|Downloading files for server type Live
2023-08-20 12:16:00.6502|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Updating installed localizations...
2023-08-20 12:16:00.6562|Warn|WoWsShipBuilder.Core.HttpClients.AwsClient|Downloading files for server type Live
2023-08-20 12:16:01.1599|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Updating images. Can delta update: false
2023-08-20 12:16:08.5473|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Completed update check
2023-08-20 12:16:08.5473|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Checking installed localization files...
2023-08-20 12:16:08.5473|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Selected localization is installed
2023-08-20 12:16:08.5473|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Starting data validation...
2023-08-20 12:16:08.6121|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Data validation successful
2023-08-20 12:16:08.6121|Info|WoWsShipBuilder.Core.DataProvider.Updater.LocalDataUpdater|Completed update check run
2023-08-20 12:16:08.6487|Info|WoWsShipBuilder|Cleared all appdata caches
2023-08-20 12:16:09.6252|Info|WoWsShipBuilder|Checked scaling for window "WoWs Ship Builder" with result false and factor 0
2023-08-20 12:16:26.6974|Info|WoWsShipBuilder.UI.App|App updated to version 2.1.24
2023-08-20 12:16:28.8039|Info|WoWsShipBuilder.UI.App|User decided to restart after update
2023-08-20 12:16:29.9213|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2023-08-20 12:16:29.9500|Info|Microsoft.Hosting.Lifetime|Hosting environment: "Production"
2023-08-20 12:16:29.9500|Info|Microsoft.Hosting.Lifetime|Content root path: "C:\Users\Daniel\AppData\Local\WoWsShipBuilder\app-2.1.24"
2023-08-20 12:16:30.7383|Info|WoWsShipBuilder.Desktop.Infrastructure.DesktopSettingsAccessor|Trying to load settings from settings file...
2023-08-20 12:16:30.9699|Info|WoWsShipBuilder.Desktop.App|AutoUpdate Enabled: true
2023-08-20 12:16:30.9699|Info|WoWsShipBuilder.Desktop.App|Current version: 2.1.24.0
2023-08-20 12:16:30.9699|Info|WoWsShipBuilder.Desktop.App|Update manager initialized
2023-08-20 12:16:31.2314|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|UpdateCheck triggered. Checking whether update should execute...
2023-08-20 12:16:31.2314|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Starting update check...
2023-08-20 12:16:31.2314|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Checking json file versions for server type "Live"
2023-08-20 12:16:31.3531|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Completed update check
2023-08-20 12:16:31.3531|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Checking installed localization files...
2023-08-20 12:16:31.3566|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Selected localization is installed
2023-08-20 12:16:31.3566|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Starting data validation...
2023-08-20 12:16:31.3861|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Data validation successful
2023-08-20 12:16:31.3861|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Completed update check run
2023-08-20 12:16:31.4091|Info|WoWsShipBuilder|Cleared all appdata caches
2023-08-20 12:16:32.0150|Info|WoWsShipBuilder.Desktop.App|No app update found
2023-08-20 12:16:32.0150|Info|WoWsShipBuilder.Desktop.App|Finished updatecheck
2023-08-20 12:18:28.3542|Info|WoWsShipBuilder.Desktop.App|Closing app, saving setting and builds
2023-08-20 12:18:28.3725|Info|WoWsShipBuilder.Desktop.App|Exiting...
2023-08-20 12:18:28.3725|Info|WoWsShipBuilder.Desktop.App|------------------------------
2023-08-20 12:18:28.3725|Info|WoWsShipBuilder.Desktop.Program|Application is shutting down.
2023-08-20 12:18:28.3725|Info|WoWsShipBuilder.Desktop.Program|------------------------------

2023-08-20 12:18:28.3871|Info|Microsoft.Hosting.Lifetime|Application is shutting down...
```
</details>

<details>
<summary>New install still not working</summary>

```
2023-08-20 13:45:12.8929|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2023-08-20 13:45:12.9151|Info|Microsoft.Hosting.Lifetime|Hosting environment: "Production"
2023-08-20 13:45:12.9201|Info|Microsoft.Hosting.Lifetime|Content root path: "C:\Windows\ImmersiveControlPanel"
2023-08-20 13:45:13.0661|Info|WoWsShipBuilder.Desktop.Program|App is uninstalling...
2023-08-20 13:45:54.9817|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2023-08-20 13:45:55.0124|Info|Microsoft.Hosting.Lifetime|Hosting environment: "Production"
2023-08-20 13:45:55.0124|Info|Microsoft.Hosting.Lifetime|Content root path: "C:\Users\REDACTED\AppData\Local\WoWsShipBuilder\app-2.1.24"
2023-08-20 13:45:55.1402|Info|WoWsShipBuilder.Desktop.Program|App has been installed, creating shortcuts...
2023-08-20 13:45:55.3286|Info|WoWsShipBuilder.Desktop.Program|Shortcuts have been created.
2023-08-20 13:45:55.7182|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2023-08-20 13:45:55.7470|Info|Microsoft.Hosting.Lifetime|Hosting environment: "Production"
2023-08-20 13:45:55.7470|Info|Microsoft.Hosting.Lifetime|Content root path: "C:\Users\REDACTED\AppData\Local\WoWsShipBuilder\app-2.1.24"
2023-08-20 13:45:56.5943|Info|WoWsShipBuilder.Desktop.Infrastructure.DesktopSettingsAccessor|Trying to load settings from settings file...
2023-08-20 13:45:56.8148|Info|WoWsShipBuilder.Desktop.App|AutoUpdate Enabled: true
2023-08-20 13:45:56.8148|Info|WoWsShipBuilder.Desktop.App|Current version: 2.1.24.0
2023-08-20 13:45:56.8148|Info|WoWsShipBuilder.Desktop.App|Update manager initialized
2023-08-20 13:45:57.0717|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|UpdateCheck triggered. Checking whether update should execute...
2023-08-20 13:45:57.0717|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Starting update check...
2023-08-20 13:45:57.0774|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Checking json file versions for server type "Live"
2023-08-20 13:45:57.2442|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Completed update check
2023-08-20 13:45:57.2442|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Checking installed localization files...
2023-08-20 13:45:57.2474|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Selected localization is installed
2023-08-20 13:45:57.2474|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Starting data validation...
2023-08-20 13:45:57.2751|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Data validation successful
2023-08-20 13:45:57.2751|Info|WoWsShipBuilder.Desktop.Features.Updater.LocalDataUpdater|Completed update check run
2023-08-20 13:45:57.2987|Info|WoWsShipBuilder|Cleared all appdata caches
2023-08-20 13:45:58.1325|Info|WoWsShipBuilder.Desktop.App|No app update found
2023-08-20 13:45:58.1325|Info|WoWsShipBuilder.Desktop.App|Finished updatecheck
2023-08-20 13:46:14.4278|Info|WoWsShipBuilder.Desktop.App|Closing app, saving setting and builds
2023-08-20 13:46:14.4482|Info|WoWsShipBuilder.Desktop.App|Exiting...
2023-08-20 13:46:14.4482|Info|WoWsShipBuilder.Desktop.App|------------------------------
2023-08-20 13:46:14.4602|Info|WoWsShipBuilder.Desktop.Program|Application is shutting down.
2023-08-20 13:46:14.4602|Info|WoWsShipBuilder.Desktop.Program|------------------------------

2023-08-20 13:46:14.4602|Info|Microsoft.Hosting.Lifetime|Application is shutting down...```

I'll later try installing while deactivating the Firewall and Antivirus (using the basic Windows Defender) and report again.

**Comment by QuantumQuacken** [comment]
Hello,
I still have the same issue. I tried running the app via Debug in VS and here's some more info about the issue.

Exception caught in RunProgram():
_"Exception has been thrown by the target of an invocation."_
StackTrace:
```
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at WoWsShipBuilder.Desktop.Program.<RunProgram>d__1.MoveNext() in D:\Git\WoWs-ShipBuilder\WoWsShipBuilder.Desktop\Program.cs:line 61
   at WoWsShipBuilder.Desktop.Program.<RunProgram>d__1.MoveNext() in D:\Git\WoWs-ShipBuilder\WoWsShipBuilder.Desktop\Program.cs:line 73
   at WoWsShipBuilder.Desktop.Program.Main(String[] args) in D:\Git\WoWs-ShipBuilder\WoWsShipBuilder.Desktop\Program.cs:line 35
```
InnerException:
_"Couldn't find a compatible Webview2 Runtime installation to host WebViews."_
StackTrace:
```
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<TryInitializeWebView2>d__15.MoveNext()
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.<>c__DisplayClass13_0.<<NavigateCore>b__0>d.MoveNext()
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.<InvokeAsync>d__5.MoveNext()
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.WindowsFormsDispatcher.<>c.<.cctor>b__8_0(Exception exception)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```
InnerException of InnerException :
_"The system cannot find the file specified. (0x80070002)"_

Take this with a grain of salt, as I have not dug deep, but it seems the problems arise from the asynchronously invoked Action at L49 in `SplashScreen.axaml.cs`.

I also tried reinstalling the latest `.NET Desktop Runtime`, version 8.0.11, to no avail.

If you need more information let me know. I can also hop on a call to verify anything together.

**Comment by floribe2000** [comment]
> Couldn't find a compatible Webview2 Runtime installation to host WebViews.

Do you have Microsoft Edge installed? This is a common issue when Edge was disabled/removed because it is the default WebView2 provider on windows.

Usually, you can resolve that by manually installing the WebView2 component.

Unfortunately, we depend on the WebView in order to reduce the development overhead for both desktop and web versions.

**Comment by QuantumQuacken** [comment]
> Usually, you can resolve that by manually installing the WebView2 component.

I had issues in the past with it and fiddled with it. Now I removed it completely and reinstalled it again, fixing the issue.

> Unfortunately, we depend on the WebView in order to reduce the development overhead for both desktop and web versions.

That's understandable.

Thank you for the help!
